environment: preprod

api:
  replicaCount: 1
  image:
    repository: thedoublemz/predictive-maintenance-api
    tag: latest
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "256m"
